[project]
name = "caltechthesis-instance"
description = "CaltechTHESIS InvenioRDM Instance"
readme = "README.md"
version = "14.0.4"
requires-python = "~= 3.14.0"

dependencies = [
  "invenio-app-rdm[opensearch2,s3]~=14.0.4",
  "invenio-saml",
  "caltechthesis",
  "granian",
  "lxml-html-clean>=0.1.1",
  "python-dotenv",
  "sentry-sdk",
]

[tool.uv.sources]
caltechthesis = { workspace = true }

[tool.uv.workspace]
members = ["site"]

[project.optional-dependencies]
tests = [
  "pytest-invenio>=4.0.0,<5.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
bypass-selection = true
